package storage

import (
	"context"
	"time"

	"ai-static-host/api/internal/domain"
)

type Store interface {
	GetUserByEmail(ctx context.Context, email string) (domain.User, bool, error)
	GetUserBySessionToken(ctx context.Context, token string) (domain.User, bool, error)
	GetUserByID(ctx context.Context, userID string) (domain.User, bool, error)
	UpdateUserUsername(ctx context.Context, userID, username string) (domain.User, error)
	UpdateUserRoleAndPlan(ctx context.Context, userID, role, planCode string) (domain.User, error)
	SyncProjectUsernames(ctx context.Context, userID, username string) error
	CreateOrRefreshAuthCode(ctx context.Context, input domain.AuthCodeRequestInput, code string, expiresAt time.Time) error
	ConsumeAuthCode(ctx context.Context, input domain.AuthCodeVerifyInput, now time.Time) (domain.User, bool, error)
	CreateProjectEmailCode(ctx context.Context, projectID, ownerUserID, email, purpose, code string, expiresAt, now time.Time, dailyLimit int) (int, error)
	ConsumeProjectEmailCode(ctx context.Context, projectID, email, purpose, code string, now time.Time) (bool, error)
	CreateSession(ctx context.Context, userID, token string, expiresAt time.Time) error
	DeleteSession(ctx context.Context, token string) error
	ListAdminUsers(ctx context.Context) ([]domain.AdminUserSummary, error)
	ListProjects(ctx context.Context, userID string) ([]domain.Project, error)
	ListPublicProjects(ctx context.Context) ([]domain.Project, error)
	GetPublicProject(ctx context.Context, projectID string) (domain.Project, bool, error)
	GetAuthorProfile(ctx context.Context, username string) (domain.AuthorProfile, bool, error)
	IsFollowingAuthor(ctx context.Context, followerUserID, targetUsername string) (bool, error)
	FollowAuthor(ctx context.Context, followerUserID, targetUsername string) error
	UnfollowAuthor(ctx context.Context, followerUserID, targetUsername string) error
	ListFollowedAuthors(ctx context.Context, followerUserID string) ([]domain.AuthorSummary, error)
	ListAuthorFollowerRecipients(ctx context.Context, authorUsername string) ([]domain.NotificationRecipient, error)
	TryCreateProjectNotificationEvent(ctx context.Context, projectID, eventKey string) (bool, error)
	IsProjectFavorited(ctx context.Context, userID, projectID string) (bool, error)
	AddProjectFavorite(ctx context.Context, userID, projectID string) error
	RemoveProjectFavorite(ctx context.Context, userID, projectID string) error
	ListUserFavoriteProjects(ctx context.Context, userID string) ([]domain.Project, error)
	ListProjectDiscussions(ctx context.Context, projectID, status, query string) ([]domain.ProjectDiscussion, error)
	GetProjectDiscussion(ctx context.Context, discussionID string) (domain.ProjectDiscussion, bool, error)
	CreateProjectDiscussion(ctx context.Context, projectID, authorUserID string, input domain.ProjectDiscussionCreateInput) (domain.ProjectDiscussion, error)
	UpdateProjectDiscussionStatus(ctx context.Context, discussionID, status, operatorUserID string) (domain.ProjectDiscussion, bool, error)
	ListProjectDiscussionComments(ctx context.Context, discussionID string) ([]domain.ProjectDiscussionComment, error)
	CreateProjectDiscussionComment(ctx context.Context, discussionID, authorUserID string, input domain.ProjectDiscussionCommentCreateInput) (domain.ProjectDiscussionComment, error)
	ListProjectProposalsForSource(ctx context.Context, sourceProjectID string) ([]domain.ProjectProposal, error)
	ListProjectProposalsForTarget(ctx context.Context, targetProjectID, status string) ([]domain.ProjectProposal, error)
	ListUserProjectProposals(ctx context.Context, userID string) ([]domain.ProjectProposal, error)
	GetProjectProposal(ctx context.Context, proposalID string) (domain.ProjectProposal, bool, error)
	CreateProjectProposal(ctx context.Context, input domain.ProjectProposal) (domain.ProjectProposal, error)
	ReviewProjectProposal(ctx context.Context, proposalID, status, note, reviewedByUserID, mergedReleaseID string) (domain.ProjectProposal, bool, error)
	CreateForkProject(ctx context.Context, userID string, input domain.ProjectCreateInput, source domain.Project) (domain.Project, error)
	ListAdminProjects(ctx context.Context) ([]domain.AdminProjectSummary, error)
	CreateProject(ctx context.Context, userID string, input domain.ProjectCreateInput) (domain.Project, error)
	GetProject(ctx context.Context, userID, projectID string) (domain.Project, bool, error)
	DeleteProject(ctx context.Context, userID, projectID string) (bool, error)
	GetProjectPublicAccess(ctx context.Context, projectID string) (domain.PublicProjectAccess, bool, error)
	CreateContestSubmission(ctx context.Context, input domain.ContestSubmission) (domain.ContestSubmission, error)
	GetContestSubmissionByUserProject(ctx context.Context, userID, projectID string) (domain.ContestSubmission, bool, error)
	ListAdminContestSubmissions(ctx context.Context, status string) ([]domain.ContestSubmission, error)
	UpdateContestSubmissionReview(ctx context.Context, submissionID, status, adminNote, reviewedBy string) (domain.ContestSubmission, error)
	UpdateProjectVisibility(ctx context.Context, userID, projectID, visibility string) (domain.Project, bool, error)
	UpdateProjectPath(ctx context.Context, userID, projectID, slug string) (domain.Project, bool, error)
	UpdateProjectSettings(ctx context.Context, userID, projectID string, input domain.ProjectSettingsUpdateInput) (domain.Project, bool, error)
	GetAppBuildSettings(ctx context.Context, userID, projectID string) (domain.AppBuildSettings, bool, error)
	UpsertAppBuildSettings(ctx context.Context, userID, projectID string, input domain.AppBuildSettingsInput) (domain.AppBuildSettings, error)
	CreateAppBuildJob(ctx context.Context, input domain.AppBuildJob) (domain.AppBuildJob, error)
	GetAppBuildJob(ctx context.Context, jobID string) (domain.AppBuildJob, bool, error)
	ListAppBuildJobs(ctx context.Context, userID, projectID string) ([]domain.AppBuildJob, error)
	CountAppBuildJobsForUserSince(ctx context.Context, userID, platform string, since time.Time) (int, error)
	CompleteAppBuildJob(ctx context.Context, jobID string, input domain.AppBuildCompleteInput) (domain.AppBuildJob, bool, error)
	GetAppUpdateInfo(ctx context.Context, projectID, platform string, versionCode int) (domain.AppUpdateInfo, error)
	ListCollections(ctx context.Context, projectID string) ([]domain.Collection, error)
	CreateCollection(ctx context.Context, projectID string, input domain.CollectionCreateInput) (domain.Collection, error)
	GetCollectionByName(ctx context.Context, projectID, collectionName string) (domain.Collection, bool, error)
	UpdateCollection(ctx context.Context, projectID, collectionName string, input domain.CollectionUpdateInput) (domain.Collection, bool, error)
	DeleteCollection(ctx context.Context, projectID, collectionName string) error
	ListRecords(ctx context.Context, projectID, collectionName string) ([]domain.Record, error)
	CreateRecord(ctx context.Context, projectID, collectionName, createdByUserID string, input domain.RecordCreateInput) (domain.Record, error)
	GetRecord(ctx context.Context, projectID, collectionName, recordID string) (domain.Record, bool, error)
	UpdateRecord(ctx context.Context, projectID, collectionName, recordID string, input domain.RecordUpdateInput) (domain.Record, bool, error)
	DeleteRecord(ctx context.Context, projectID, collectionName, recordID string) (bool, error)
	ProjectDataStats(ctx context.Context, projectID string) (domain.ProjectDataStats, error)
	GetMonthlyProjectUsage(ctx context.Context, projectID, monthKey string) (domain.ProjectUsage, error)
	IncrementProjectUsage(ctx context.Context, projectID, monthKey string, queryDelta, writeDelta int64) (domain.ProjectUsage, error)
	IncrementProjectDailyStats(ctx context.Context, projectID, day string, pageViews, apiRequests, apiSuccesses, apiFailures int64) error
	ProjectStats(ctx context.Context, projectID, from, to string) (domain.ProjectStatsSummary, error)
	CreateProjectDomain(ctx context.Context, input domain.ProjectDomain) (domain.ProjectDomain, error)
	ListProjectDomains(ctx context.Context, projectID string) ([]domain.ProjectDomain, error)
	ListAdminProjectDomains(ctx context.Context, status string) ([]domain.ProjectDomain, error)
	GetActiveProjectDomainAccessByDomain(ctx context.Context, host string) (domain.ProjectDomain, domain.Project, bool, error)
	UpdateProjectDomainReview(ctx context.Context, domainID, status, rejectReason, adminNote, reviewedBy string) (domain.ProjectDomain, error)
	CreateProjectDomainDeleteRequest(ctx context.Context, input domain.ProjectDomainDeleteRequest) (domain.ProjectDomainDeleteRequest, error)
	ListProjectDomainDeleteRequests(ctx context.Context, projectID string) ([]domain.ProjectDomainDeleteRequest, error)
	ListAdminProjectDomainDeleteRequests(ctx context.Context, status string) ([]domain.ProjectDomainDeleteRequest, error)
	UpdateProjectDomainDeleteRequest(ctx context.Context, requestID, status, adminNote, reviewedBy string) (domain.ProjectDomainDeleteRequest, error)
	CreateRepairRequest(ctx context.Context, input domain.RepairRequest) (domain.RepairRequest, error)
	ListProjectRepairRequests(ctx context.Context, projectID string) ([]domain.RepairRequest, error)
	ListAdminRepairRequests(ctx context.Context, status string) ([]domain.RepairRequest, error)
	UpdateRepairRequest(ctx context.Context, requestID, status, adminReply, reviewedBy string) (domain.RepairRequest, error)
	ReplyRepairRequest(ctx context.Context, projectID, requestID, reply string) (domain.RepairRequest, error)
	GetRepairRequest(ctx context.Context, projectID, requestID string) (domain.RepairRequest, bool, error)
	CreateRepairAIJob(ctx context.Context, input domain.RepairAIJob) (domain.RepairAIJob, error)
	GetRepairAIJob(ctx context.Context, jobID string) (domain.RepairAIJob, bool, error)
	GetLatestRepairAIJob(ctx context.Context, repairRequestID string) (domain.RepairAIJob, bool, error)
	ListRepairAIJobs(ctx context.Context, repairRequestID string) ([]domain.RepairAIJob, error)
	GetActiveRepairAIJobByUser(ctx context.Context, userID string) (domain.RepairAIJob, bool, error)
	CountRepairAIJobsForUserSince(ctx context.Context, userID string, since time.Time) (int, error)
	UpdateRepairAIJob(ctx context.Context, job domain.RepairAIJob) (domain.RepairAIJob, error)
	CreateRepairAIMessage(ctx context.Context, input domain.RepairAIMessage) (domain.RepairAIMessage, error)
	ListRepairAIMessages(ctx context.Context, jobID string) ([]domain.RepairAIMessage, error)
	IsReservedSubdomain(ctx context.Context, subdomain string) (bool, error)
	CreateTemplateSubmission(ctx context.Context, input domain.TemplateSubmission) (domain.TemplateSubmission, error)
	ListPublishedTemplateSubmissions(ctx context.Context) ([]domain.TemplateSubmission, error)
	ListMyTemplateSubmissions(ctx context.Context, userID string) ([]domain.TemplateSubmission, error)
	ListAdminTemplateSubmissions(ctx context.Context, status string) ([]domain.TemplateSubmission, error)
	GetTemplateSubmission(ctx context.Context, submissionID string) (domain.TemplateSubmission, bool, error)
	GetPublishedTemplateSubmissionByIDOrSlug(ctx context.Context, idOrSlug string) (domain.TemplateSubmission, bool, error)
	UpdateTemplateSubmissionReview(ctx context.Context, submissionID, status, adminNote, reviewedBy string) (domain.TemplateSubmission, error)
	CreateUpgradeRequest(ctx context.Context, input domain.UpgradeRequest) (domain.UpgradeRequest, error)
	ListUpgradeRequests(ctx context.Context) ([]domain.UpgradeRequest, error)
	ListUserUpgradeRequests(ctx context.Context, userID string) ([]domain.UpgradeRequest, error)
	UpdateUpgradeRequest(ctx context.Context, requestID, status, adminNote, reviewedBy string) (domain.UpgradeRequest, error)
	CreateRelease(ctx context.Context, release domain.Release) (domain.Release, error)
	ListReleases(ctx context.Context, projectID string) ([]domain.Release, error)
	SetCurrentRelease(ctx context.Context, projectID, releaseID string) error
}
