package http

func renderMessageBoardTemplate(values map[string]string, projectID, publicKey string, preview bool) string {
	cfg := templateRuntimeConfig(projectID, publicKey, preview)
	return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>` + values["siteTitle"] + `</title><style>
:root{--theme:` + values["themeColor"] + `}body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#fff7ed;color:#211812}.wrap{width:min(860px,calc(100vw - 32px));margin:0 auto;padding:48px 0}h1{margin:0;color:var(--theme);font-size:clamp(2rem,7vw,3.5rem)}p{line-height:1.7}.panel{background:#fff;border:1px solid #ead7c4;border-radius:24px;padding:22px;margin-top:18px;box-shadow:0 14px 40px rgba(120,72,24,.08)}label{display:grid;gap:6px;margin-bottom:12px}input,textarea,button{font:inherit}input,textarea{width:100%;padding:12px;border:1px solid #decbb8;border-radius:14px}button{border:0;border-radius:999px;padding:12px 18px;background:var(--theme);color:#fff;font-weight:700}.msg{border-top:1px solid #f1e1cf;padding:14px 0}.meta{color:#7c6f64;font-size:.92rem}</style></head><body><main class="wrap"><h1>` + values["siteTitle"] + `</h1><p>` + values["subtitle"] + `</p><section class="panel"><form id="form"><label>昵称<input id="nickname" required maxlength="40"></label><label>留言<textarea id="content" required rows="4" maxlength="1000"></textarea></label><button>发送留言</button></form><div id="status" role="status" aria-live="polite"></div></section><section class="panel"><h2>留言</h2><div id="list">正在读取留言……</div></section></main><script>const CFG=` + cfg + `;
const api=(p)=>CFG.apiBase+p;const headers={'Content-Type':'application/json','X-Project-Key':CFG.publicKey};
const previewMessages=[{id:'preview-msg-1',data:{nickname:'小明',content:'这个留言板可以用来收集反馈。'},createdAt:new Date(Date.now()-86400000).toISOString()},{id:'preview-msg-2',data:{nickname:'小红',content:'当前是模板预览，留言只会临时显示。'},createdAt:new Date().toISOString()}];
function esc(s){return String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function request(path,opt={}){if(CFG.preview){return previewRequest(path,opt)}const r=await fetch(api(path),{...opt,headers:{...headers,...opt.headers}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'请求失败');return j}
async function previewRequest(path,opt={}){await new Promise(r=>setTimeout(r,120));if(path==='/collections/messages/records'&&(!opt.method||opt.method==='GET'))return{items:previewMessages};if(path==='/collections/messages/records'&&opt.method==='POST'){const body=JSON.parse(opt.body||'{}');previewMessages.push({id:'preview-msg-'+(previewMessages.length+1),data:body.data||{},createdAt:new Date().toISOString()});return previewMessages[previewMessages.length-1]}throw new Error('预览模式不支持这个操作')}
async function load(){try{const data=await request('/collections/messages/records');const items=(data.items||[]).slice().reverse();list.innerHTML=items.length?items.map(x=>'<article class="msg"><strong>'+esc(x.data.nickname)+'</strong><div>'+esc(x.data.content)+'</div><div class="meta">'+new Date(x.createdAt).toLocaleString()+'</div></article>').join(''):'还没有留言。'}catch(e){list.textContent=e.message}}
form.addEventListener('submit',async e=>{e.preventDefault();status.textContent='正在发送……';try{await request('/collections/messages/records',{method:'POST',body:JSON.stringify({data:{nickname:nickname.value.trim(),content:content.value.trim()}})});content.value='';status.textContent=CFG.preview?'预览留言已临时显示，刷新后会恢复默认演示数据。':'已发送。';await load()}catch(err){status.textContent=err.message}});load();</script></body></html>`
}
