package http

func renderMiniForumTemplate(values map[string]string, projectID, publicKey string, preview bool) string {
	cfg := templateRuntimeConfig(projectID, publicKey, preview)
	return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>` + values["siteTitle"] + `</title><style>
:root{--theme:` + values["themeColor"] + `}body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#eff6ff;color:#172033}.wrap{width:min(960px,calc(100vw - 32px));margin:0 auto;padding:42px 0}h1{color:var(--theme);font-size:clamp(2rem,7vw,3.5rem);margin:0}.panel,.post{background:#fff;border:1px solid #dbeafe;border-radius:22px;padding:20px;margin-top:16px;box-shadow:0 12px 36px rgba(30,64,175,.08)}label{display:grid;gap:6px;margin-bottom:10px}input,textarea,button{font:inherit}input,textarea{width:100%;padding:12px;border:1px solid #bfdbfe;border-radius:14px}button{border:0;border-radius:999px;padding:10px 16px;background:var(--theme);color:#fff;font-weight:700}.muted{color:#64748b}.comment{border-top:1px solid #e0edff;margin-top:10px;padding-top:10px}</style></head><body><main class="wrap"><h1>` + values["siteTitle"] + `</h1><p class="muted">` + values["subtitle"] + `</p><section class="panel"><h2>发布新帖</h2><form id="postForm"><label>昵称<input id="author" required maxlength="40"></label><label>标题<input id="title" required maxlength="80"></label><label>内容<textarea id="content" required rows="4" maxlength="2000"></textarea></label><button>发布</button></form><div id="status" role="status" aria-live="polite"></div></section><section id="posts"></section></main><script>const CFG=` + cfg + `;
const api=(p)=>CFG.apiBase+p;const headers={'Content-Type':'application/json','X-Project-Key':CFG.publicKey};let allComments=[];
const previewPosts=[{id:'preview-post-1',data:{author:'模板管理员',title:'欢迎来到轻论坛',content:'这里可以发布帖子，也可以回复讨论。'},createdAt:new Date(Date.now()-7200000).toISOString()},{id:'preview-post-2',data:{author:'路过的同学',title:'模板预览说明',content:'当前互动数据只存在浏览器内存里，不会保存到数据库。'},createdAt:new Date(Date.now()-3600000).toISOString()}];
const previewComments=[{id:'preview-comment-1',data:{postId:'preview-post-1',author:'小明',content:'这个模板适合做班级交流区。'},createdAt:new Date(Date.now()-1800000).toISOString()}];
function esc(s){return String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function request(path,opt={}){if(CFG.preview){return previewRequest(path,opt)}const r=await fetch(api(path),{...opt,headers:{...headers,...opt.headers}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'请求失败');return j}
async function previewRequest(path,opt={}){await new Promise(r=>setTimeout(r,120));const method=opt.method||'GET';if(path==='/collections/posts/records'&&method==='GET')return{items:previewPosts};if(path==='/collections/comments/records'&&method==='GET')return{items:previewComments};if(path==='/collections/posts/records'&&method==='POST'){const body=JSON.parse(opt.body||'{}');const item={id:'preview-post-'+(previewPosts.length+1),data:body.data||{},createdAt:new Date().toISOString()};previewPosts.push(item);return item}if(path==='/collections/comments/records'&&method==='POST'){const body=JSON.parse(opt.body||'{}');const item={id:'preview-comment-'+(previewComments.length+1),data:body.data||{},createdAt:new Date().toISOString()};previewComments.push(item);return item}throw new Error('预览模式不支持这个操作')}
async function load(){posts.textContent='正在读取帖子……';try{const [p,c]=await Promise.all([request('/collections/posts/records'),request('/collections/comments/records')]);allComments=c.items||[];const items=(p.items||[]).slice().reverse();posts.innerHTML=items.length?items.map(renderPost).join(''):'<section class="panel">还没有帖子。</section>';document.querySelectorAll('[data-reply]').forEach(btn=>btn.addEventListener('click',reply))}catch(e){posts.innerHTML='<section class="panel">'+esc(e.message)+'</section>'}}
function renderPost(x){const cs=allComments.filter(c=>c.data.postId===x.id);return '<article class="post"><h2>'+esc(x.data.title)+'</h2><p>'+esc(x.data.content)+'</p><p class="muted">'+esc(x.data.author)+' · '+new Date(x.createdAt).toLocaleString()+'</p><button data-reply="'+x.id+'">回复</button><div>'+cs.map(c=>'<div class="comment"><strong>'+esc(c.data.author)+'</strong>：'+esc(c.data.content)+'</div>').join('')+'</div></article>'}
async function reply(e){const postId=e.target.getAttribute('data-reply');const author=prompt('你的昵称')||'';if(!author.trim())return;const content=prompt('回复内容')||'';if(!content.trim())return;await request('/collections/comments/records',{method:'POST',body:JSON.stringify({data:{postId,author:author.trim(),content:content.trim()}})});await load()}
postForm.addEventListener('submit',async e=>{e.preventDefault();status.textContent='正在发布……';try{await request('/collections/posts/records',{method:'POST',body:JSON.stringify({data:{author:author.value.trim(),title:title.value.trim(),content:content.value.trim()}})});title.value='';content.value='';status.textContent=CFG.preview?'预览帖子已临时显示，刷新后会恢复默认演示数据。':'已发布。';await load()}catch(err){status.textContent=err.message}});load();</script></body></html>`
}
