package http

import "ai-static-host/api/internal/domain"

var builtInTemplates = []domain.ProjectTemplate{
	{
		ID:                   "personal-home",
		Slug:                 "personal-home",
		Name:                 "个人主页",
		Category:             "site",
		CategoryLabel:        "个人网站",
		Summary:              "适合做个人介绍、社交链接和作品展示。",
		Description:          "一个简洁的个人主页模板，包含昵称、简介、三个链接和强调色配置。适合新用户快速做一个自己的主页。",
		Tags:                 []string{"官方", "个人主页", "展示"},
		InteractiveRequired:  false,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-06-22",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "主页标题", Type: "string", Required: true, Default: "我的个人主页", Placeholder: "例如：汪汪的小站"},
			{Name: "nickname", Label: "昵称", Type: "string", Required: true, Default: "PlayPage 用户"},
			{Name: "bio", Label: "个人简介", Type: "text", Required: false, Default: "这里写一段自我介绍、兴趣或作品说明。"},
			{Name: "link1", Label: "链接一", Type: "string", Required: false, Default: "https://web.wangru.net"},
			{Name: "link2", Label: "链接二", Type: "string", Required: false, Default: ""},
			{Name: "link3", Label: "链接三", Type: "string", Required: false, Default: ""},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#7c3aed"},
		},
	},
	{
		ID:                   "link-directory",
		Slug:                 "link-directory",
		Name:                 "资源导航页",
		Category:             "site",
		CategoryLabel:        "个人网站",
		Summary:              "把常用网站、资料、作品链接整理成一个导航页。",
		Description:          "适合做班级资源导航、个人收藏夹、项目入口页。先提供 6 个链接位，后续可以再扩展为可编辑数据表版本。",
		Tags:                 []string{"官方", "导航", "资源"},
		InteractiveRequired:  false,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-06-22",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "导航标题", Type: "string", Required: true, Default: "我的资源导航"},
			{Name: "subtitle", Label: "说明文字", Type: "text", Required: false, Default: "把常用链接集中放在这里。"},
			{Name: "link1Title", Label: "链接1标题", Type: "string", Required: false, Default: "PlayPage"},
			{Name: "link1Url", Label: "链接1地址", Type: "string", Required: false, Default: "https://web.wangru.net"},
			{Name: "link2Title", Label: "链接2标题", Type: "string", Required: false, Default: "我的作品"},
			{Name: "link2Url", Label: "链接2地址", Type: "string", Required: false, Default: "https://web.wangru.net/projects"},
			{Name: "link3Title", Label: "链接3标题", Type: "string", Required: false, Default: "模板市场"},
			{Name: "link3Url", Label: "链接3地址", Type: "string", Required: false, Default: "https://web.wangru.net/templates"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#0f766e"},
		},
	},
	{
		ID:                   "message-board",
		Slug:                 "message-board",
		Name:                 "留言板",
		Category:             "interactive",
		CategoryLabel:        "互动作品",
		Summary:              "带云端保存的简单留言板，适合反馈、祝福墙、班级留言。",
		Description:          "创建后会自动开启互动功能并创建 messages 数据表。访客可以填写昵称和留言，留言会保存到作品数据表。",
		Tags:                 []string{"官方", "留言", "互动"},
		InteractiveRequired:  true,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-06-22",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "留言板标题", Type: "string", Required: true, Default: "我的留言板"},
			{Name: "subtitle", Label: "说明文字", Type: "text", Required: false, Default: "欢迎留下你的想法。"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#d6652f"},
		},
		Collections: []domain.TemplateCollectionDefinition{
			{
				Name:        "messages",
				Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
				Fields: []domain.FieldSchema{
					{Name: "nickname", Type: "string", Required: true},
					{Name: "content", Type: "text", Required: true},
				},
			},
		},
	},
	{
		ID:                   "mini-forum",
		Slug:                 "mini-forum",
		Name:                 "轻论坛",
		Category:             "interactive",
		CategoryLabel:        "互动作品",
		Summary:              "一个轻量论坛模板，支持发帖和回复。",
		Description:          "创建后会自动开启互动功能并创建 posts、comments 数据表。适合小圈子讨论、班级交流、项目问答。",
		Tags:                 []string{"官方", "论坛", "互动"},
		InteractiveRequired:  true,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-06-22",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "论坛标题", Type: "string", Required: true, Default: "我的轻论坛"},
			{Name: "subtitle", Label: "论坛简介", Type: "text", Required: false, Default: "发帖、回复，开始交流。"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#2563eb"},
		},
		Collections: []domain.TemplateCollectionDefinition{
			{
				Name:        "posts",
				Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
				Fields: []domain.FieldSchema{
					{Name: "title", Type: "string", Required: true},
					{Name: "content", Type: "text", Required: true},
					{Name: "author", Type: "string", Required: true},
				},
			},
			{
				Name:        "comments",
				Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
				Fields: []domain.FieldSchema{
					{Name: "postId", Type: "string", Required: true},
					{Name: "content", Type: "text", Required: true},
					{Name: "author", Type: "string", Required: true},
				},
			},
		},
	},
	{
		ID:                   "feedback-center",
		Slug:                 "feedback-center",
		Name:                 "问题反馈",
		Category:             "interactive",
		CategoryLabel:        "互动作品",
		Summary:              "访客可以提交问题、建议或报错，适合作品反馈入口。",
		Description:          "创建后会自动开启互动功能并创建 feedbacks 数据表。访客提交的问题会保存到云端，站长可以在互动数据页面查看和处理。",
		Tags:                 []string{"官方", "反馈", "工单", "互动"},
		InteractiveRequired:  true,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-07-02",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "页面标题", Type: "string", Required: true, Default: "问题反馈"},
			{Name: "subtitle", Label: "说明文字", Type: "text", Required: false, Default: "遇到问题或有建议，可以在这里提交。"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#dc2626"},
		},
		Collections: []domain.TemplateCollectionDefinition{{
			Name:        "feedbacks",
			Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
			Fields: []domain.FieldSchema{
				{Name: "nickname", Type: "string", Required: true},
				{Name: "title", Type: "string", Required: true},
				{Name: "content", Type: "text", Required: true},
				{Name: "contact", Type: "string", Required: false},
				{Name: "status", Type: "string", Required: false},
				{Name: "reply", Type: "text", Required: false},
			},
		}},
	},
	{
		ID:                   "game-scoreboard",
		Slug:                 "game-scoreboard",
		Name:                 "游戏排行榜",
		Category:             "interactive",
		CategoryLabel:        "互动作品",
		Summary:              "给小游戏配一个云端排行榜，支持玩家提交分数。",
		Description:          "创建后会自动开启互动功能并创建 scores 数据表。适合小游戏、竞速挑战、答题挑战等作品展示成绩。",
		Tags:                 []string{"官方", "游戏", "排行榜", "互动"},
		InteractiveRequired:  true,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-07-02",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "排行榜标题", Type: "string", Required: true, Default: "游戏排行榜"},
			{Name: "subtitle", Label: "说明文字", Type: "text", Required: false, Default: "提交你的成绩，看看谁排在前面。"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#f59e0b"},
		},
		Collections: []domain.TemplateCollectionDefinition{{
			Name:        "scores",
			Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
			Fields: []domain.FieldSchema{
				{Name: "player", Type: "string", Required: true},
				{Name: "score", Type: "string", Required: true},
				{Name: "note", Type: "text", Required: false},
			},
		}},
	},
	{
		ID:                   "announcement-log",
		Slug:                 "announcement-log",
		Name:                 "公告和更新日志",
		Category:             "interactive",
		CategoryLabel:        "互动作品",
		Summary:              "发布公告、版本更新和维护说明。",
		Description:          "创建后会自动开启互动功能并创建 announcements 数据表。适合作品官网、工具站、社团主页展示更新动态。",
		Tags:                 []string{"官方", "公告", "更新日志", "互动"},
		InteractiveRequired:  true,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-07-02",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "页面标题", Type: "string", Required: true, Default: "公告和更新日志"},
			{Name: "subtitle", Label: "说明文字", Type: "text", Required: false, Default: "记录重要公告和每次更新内容。"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#2563eb"},
		},
		Collections: []domain.TemplateCollectionDefinition{{
			Name:        "announcements",
			Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
			Fields: []domain.FieldSchema{
				{Name: "title", Type: "string", Required: true},
				{Name: "version", Type: "string", Required: false},
				{Name: "content", Type: "text", Required: true},
			},
		}},
	},
	{
		ID:                   "event-registration",
		Slug:                 "event-registration",
		Name:                 "活动报名",
		Category:             "interactive",
		CategoryLabel:        "互动作品",
		Summary:              "活动介绍加报名表，报名信息保存到云端。",
		Description:          "创建后会自动开启互动功能并创建 registrations 数据表。适合班级活动、社团活动、线上招募和小型预约。",
		Tags:                 []string{"官方", "报名", "活动", "互动"},
		InteractiveRequired:  true,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-07-02",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "活动标题", Type: "string", Required: true, Default: "活动报名"},
			{Name: "subtitle", Label: "活动说明", Type: "text", Required: false, Default: "填写信息即可报名参加。"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#16a34a"},
		},
		Collections: []domain.TemplateCollectionDefinition{{
			Name:        "registrations",
			Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
			Fields: []domain.FieldSchema{
				{Name: "nickname", Type: "string", Required: true},
				{Name: "contact", Type: "string", Required: true},
				{Name: "note", Type: "text", Required: false},
			},
		}},
	},
	{
		ID:                   "download-showcase",
		Slug:                 "download-showcase",
		Name:                 "下载和作品展示",
		Category:             "interactive",
		CategoryLabel:        "互动作品",
		Summary:              "展示软件、音乐、文档或素材下载链接。",
		Description:          "创建后会自动开启互动功能并创建 resources 数据表。适合做作品发布页、素材合集、工具下载页。",
		Tags:                 []string{"官方", "下载", "展示", "互动"},
		InteractiveRequired:  true,
		AnalyticsRecommended: true,
		UsageCount:           0,
		CreatedAtText:        "2026-07-02",
		ConfigFields: []domain.TemplateConfigField{
			{Name: "siteTitle", Label: "页面标题", Type: "string", Required: true, Default: "下载和作品展示"},
			{Name: "subtitle", Label: "说明文字", Type: "text", Required: false, Default: "整理你的作品、工具或素材下载。"},
			{Name: "themeColor", Label: "主题色", Type: "color", Required: false, Default: "#7c3aed"},
		},
		Collections: []domain.TemplateCollectionDefinition{{
			Name:        "resources",
			Permissions: domain.PermissionSet{PublicRead: true, PublicWrite: true},
			Fields: []domain.FieldSchema{
				{Name: "title", Type: "string", Required: true},
				{Name: "version", Type: "string", Required: false},
				{Name: "url", Type: "string", Required: true},
				{Name: "description", Type: "text", Required: false},
			},
		}},
	},
}
